video_dir: "/workspace/own_dataset_video/"
output_folder: "scene_script"
model_path: "OpenGVLab/VideoChat-Flash-Qwen2-7B_res224"
mm_llm_compress: false
max_num_frames: 96
generation_config:
  do_sample: false
  max_new_tokens: 1024
  num_beams: 1

prompts:
  init_prompt: "The video provides an overall context. Please describe each subsequent video clip based on its content and how it connects to the rest of the video."
  clip_prompt_template: "Describe this video in detail, considering the scripts provided below:\n{script}"