paths:
  frame_json_path: "./json/frame_output_v3.json"
  scene_json_path: "./json/scene_output_v10.1.json"
  merged_json_path: "./json/merged_output_v5.json"
  embedding_json_path: "./embedding/emb_v5.json"
  input_csv_path: "./test_dataset/own_dataset_v2.csv"
  result_csv_path: "./result/result_v5.csv"
  output_score_csv_path: "./result/eval_v5.csv"

ettings:
  model_name: "BAAI/bge-m3"
  top_k: 1
  start_stage: "merge"  # [merge, embedding, retrieving, evaluation]