paths:
  result_csv: "output/opt_results.csv"
  ground_truth_csv: "own_dataset_v2.csv"
  output_score_csv: "output/opt_scores.csv"
  weights_output_csv: "output/opt_weights_results.csv"

weights:
  w_scene: 0.3
  w_clip: 0.4
  w_blip: 0.3

bayesian_optimization:
  init_points: 5  
  n_iter: 10