general:
  device: "cuda"  # 사용할 디바이스: "cuda" (GPU) 또는 "cpu"

data:
  frames_folder: "./test_dataset_79"  # 프레임 이미지 저장 경로
  output_folder: "./output"  # 분석 결과 및 출력 파일 저장 경로
  datasets_folder: "./datasets"  # 데이터셋 저장 경로
  datasets_name: "my_test_dataset"  # 데이터셋 이름
  frame_output_filename: "frame_output_v25.json"  # 프레임 캡션 결과 파일 이름
  scene_output_filename: "scene_output_v25.json"  # 씬 캡션 결과 파일 이름

model:
  model_name: "lmms-lab/LLaVA-Video-7B-Qwen2" # "OpenGVLab/InternVL2_5-4B", "unsloth/Qwen2-VL-7B-Instruct-bnb-4bit"

generation:
  prompt: "Describe the video."  # 캡셔닝 모델 프롬프트
  max_new_tokens: 128  # 생성할 최대 토큰 수
  batch_size: 6  # 배치 크기
  use_datasets: True  # 데이터셋 사용 여부

extract_frames:
  video_folder: "./video"  # 원본 비디오 파일 저장 경로 (code 기준 상위 디렉토리)
  frame_rate: 4  # 초당 추출할 프레임 수 (FPS)

extract_scenes:
  # video_folder는 extract_frames의 video_folder를 사용
  timestamp_file: "./video_timestamps.txt"  # 타임스탬프 파일 경로
  scene_folder: "./test_scenes"  # 추출된 씬 이미지 저장 경로
  generation_config: # 씬 캡션 생성 설정
    do_sample: False
    temperature: 0.5
    top_p: 0.9
    top_k: 50
    max_new_tokens: 256
    num_beams: 1

audio:
  use_audio: False  # 오디오 사용 여부
  mono_audio_folder: null  # 오디오 파일 저장 경로
  scene_info_json_file: null  # 오디오 스크립트가 포함된 Scene 정보 JSON 파일 경로