general:
  video_folder: "../video"            # 비디오 파일이 저장된 디렉토리 경로
  output_folder: "../output"           # 출력 결과를 저장할 기본 디렉토리
  key_frames_folder: "../key_frames"   # 키프레임을 저장할 디렉토리
  full_scenes_folder: "../scenes"      # 분리된 장면을 저장할 디렉토리
  audio_folder: "../audio"             # 분리된 장면별 오디오를 저장할 디렉토리

scene_detection:
  threshold: 30.0                       # 장면 전환 감지 임계값
  min_scene_len: 2                      # 최소 장면 길이 (초)