#전체 비디오 저장할곳
video_dir: "/data/ephemeral/home/sujin/own_dataset_video"
output_folder: "scene_script"
#클립저장할곳 지정
clip_output_directory: "/data/ephemeral/home/sujin/clip_description_InternVideo2_chat8B/full_clips"
#모델 지정
model_path: "OpenGVLab/InternVideo2-Chat-8B" #lmms-lab/LLaVA-Video-7B-Qwen2
#타임스탬프파일
timestamp_file: "/data/ephemeral/home/sujin/clip_description_InternVideo2_chat8B/video_timestamps.txt"


##################################################
#Configure the model -> videochatflash_model_utils.py
#mm_llm_compress: false 

#Evaluation configuration
#max_num_frames: 96 
generation_config:
  do_sample: false
  temperature: 0.5
  top_p: 0.9
  top_k: 50
  max_new_tokens: 256
  num_beams: 1
##################################################

prompt:
  clip_prompt_template: 'describe the action step by step.'

#최종 결과 저장 파일이름 설정
final_output: "clip_output_v30.json"
