video_dir: "/workspace/gs_2/video"
output_folder: "scene_script"
model_path: "OpenGVLab/VideoChat-Flash-Qwen2-7B_res224"
mm_llm_compress: false
max_num_frames: 96
generation_config:
  do_sample: false
  max_new_tokens: 256
  num_beams: 1

prompts:
  clip_prompt_template: "Describe this video in detail, considering the scripts provided below:\n"

final_output: "final_output_4.json"