video_dir: "/workspace/own_dataset_video"
output_folder: "scene_script_llava"
model_path: "OpenGVLab/VideoChat-Flash-Qwen2-7B_res224" #lmms-lab/LLaVA-Video-7B-Qwen2

##################################################
#Configure the model -> videochatflash_model_utils.py
mm_llm_compress: false 

#Evaluation configuration
max_num_frames: 96 
generation_config:
  do_sample: false
  max_new_tokens: 256
  num_beams: 1

prompt:
  clip_prompt_template: "Describe this video in detail."

#최종 결과 저장 파일이름 설정
final_output: "clip_output_v1.json"
